# Pandas 데이터 입출력
- CSV, Excel, json 파일을 읽고 저장하는 기본 흐름

In [2]:
import pandas as pd

df = pd.DataFrame({
    '상품' : ['노트북','마우스','키보드'],
    '수량' : [10,25,15],
    '단가' : [1200000,30000,50000]
})

df['총액'] = df['수량']*df['단가']
print(df)

    상품  수량       단가        총액
0  노트북  10  1200000  12000000
1  마우스  25    30000    750000
2  키보드  15    50000    750000

## CSV 읽기/저장
CSV는 가장 많이 사용하는 데이터 파일 형식이다.

In [3]:
# CSV 파일 저장
# index = False : 인덱스 값 제외하고 저장
# encoding : 한글 값 깨짐 방지
df.to_csv('sample.csv',index=False,encoding='utf-8-sig')

# CSV 읽기
df_csv = pd.read_csv('sample.csv')
print(df_csv)

# 필요한 열만 선택해서 읽기 (메모리 절약 + 속도 향상)
df_cols = pd.read_csv('sample.csv',usecols=['상품','총액'])
print(df_cols)

    상품  수량       단가        총액
0  노트북  10  1200000  12000000
1  마우스  25    30000    750000
2  키보드  15    50000    750000
    상품        총액
0  노트북  12000000
1  마우스    750000
2  키보드    750000

In [4]:
# CSV의 기본 구분자는 ',' 이지만 다른 구분자를 사용하는 파일이 있다면 sep 속성으로 처리

with open('sample_tab.txt','w',encoding='utf-8') as f:
    f.write('이름\t점수\n')
    f.write('홍길동\t80\n')
    f.write('유관순\t70\n')
    f.write('신사임당\t60\n')

df_tab = pd.read_csv('sample_tab.txt',sep='\t')
df_tab

     이름  점수
0   홍길동  80
1   유관순  70
2  신사임당  60

## Excel 읽기/저장
- Excel 파일은 'openpyxl' 라이브러리가 필요하다.
- CSV보다 구조가 복잡하며 Sheet 단위로 데이터를 관리한다.
- 특정 시트 선택, 여러 시트 저장 기능 등을 사용할 수 있다.

In [ ]:
# Excel 저장
df.to_excel('sample.xlsx', index=False,sheet_name='판매 데이터')

# Excel 읽기 (기본적으로 첫 번째 시트를 읽음)
df_excel = pd.read_excel('sample.xlsx')
df_excel

    상품  수량       단가        총액
0  노트북  10  1200000  12000000
1  마우스  25    30000    750000
2  키보드  15    50000    750000

In [8]:
# 여러 시트 저장
# ExcelWriter 를 사용해서 하나의 파일에 여러 시트를 저장할 수 있다.
summary = df[['상품','총액']]

with pd.ExcelWriter('report.xlsx') as writer:
    # 원본 데이터 시트 
    df.to_excel(writer,sheet_name='원본',index=False)
    #요약 데이터 시트
    summary.to_excel(writer,sheet_name='요약',index=False)

# with 블록 종료 시 자동으로 파일 저장
print('report.xlsx 저장 완료')

# 특정 시트 읽기
summary_excel = pd.read_excel('report.xlsx',sheet_name='요약')
summary_excel

report.xlsx 저장 완료

    상품        총액
0  노트북  12000000
1  마우스    750000
2  키보드    750000

## JSON 읽기/저장
- JSON은 key-value 형태의 데이터 구조로 API 응답이나 설정 파일에서 자주 사용된다.

In [10]:
# JSON 저장
# orient = 'records' : 각 행을 dict로 표현하는 방식으로 가장 이해하기 쉽다.
# force_ascii = False : 한글이 깨지지 않고 그대로 저장
# indent = 2 : 들여쓰기 적용
df.to_json('sample.json',orient='records',force_ascii=False,indent=2)

# JSON 읽기
df_json = pd.read_json('sample.json')
df_json

    상품  수량       단가        총액
0  노트북  10  1200000  12000000
1  마우스  25    30000    750000
2  키보드  15    50000    750000