# 데이터 전처리
- 결측값, 중복값, 정렬, 필터링, 타입 변환은 데이터 분석 전 기본적으로 수행하는 작업이다.

In [1]:
import pandas as pd
import numpy as np

## 결측값 확인
실제 데이터네는 비어있는 값이 자주 포함 된다.
이러한 결측 값을 먼저 확인해야 제거할지, 다른 값으로 채울지 판단할 수 있다.

In [4]:
df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최지영'],
    '나이': [25, np.nan, 35, 40],               # np.nan : 숫자 결측값
    '도시': ['서울', '부산', None, '대전'],       # None : 값 없음 (pandas에서는 결측값 처리)
    '급여': [4500, 5200, np.nan, 4800]
})

print(df.isna())        # na : not available -> 결측값
print()

print(df.isna().sum())  # 열별 결측 개수 확인
print()

display(df[df.isna().any(axis=1)])  # 결측값이 하나라도 있는 행만 확인

df      # 원본 확인용

      이름     나이     도시     급여
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False

이름    0
나이    1
도시    1
급여    1
dtype: int64

    이름    나이   도시      급여
1  이영희   NaN   부산  5200.0
2  박민수  35.0  NaN     NaN

    이름    나이   도시      급여
0  김철수  25.0   서울  4500.0
1  이영희   NaN   부산  5200.0
2  박민수  35.0  NaN     NaN
3  최지영  40.0   대전  4800.0

## 결측값 제거
결측값이 있는 데이터를 그대로 사용할 수 없는 경우에는 해당 행을 제거할 수 있다.
이때 모든 결측 행을 제거할 수도 있고, 특정 컬럼의 결측만 기준으로 제거할 수 있다.

In [6]:
# 결측아 포험된 행을 제거
display(df.dropna())
# 나이 컬럼의 결측만 기준으로 제거
display(df.dropna(subset=['나이']))

    이름    나이  도시      급여
0  김철수  25.0  서울  4500.0
3  최지영  40.0  대전  4800.0

    이름    나이   도시      급여
0  김철수  25.0   서울  4500.0
2  박민수  35.0  NaN     NaN
3  최지영  40.0   대전  4800.0

## 결측값 채우기
결측값으로 무조건 삭제하는 것이 아니라, 다른 값으로 채워서 유지하는 방법도 자주 사용한다.
- 예를 들어
    - 수치형 데이터는 평균이나 0으로 채우기
    - 문자열 데이터는 '미상' 같은 값 채우기
    - 시계열이나 순서가 있는 데이터는 앞의 값을 그대로 채우기

In [8]:
filled = df.fillna({
    '나이' : df['나이'].mean(),
    '도시' : '미상',
    '급여' : 0
})
display(filled)
# 앞의 행의 값을 그대로 채우기
df.ffill()

    이름         나이  도시      급여
0  김철수  25.000000  서울  4500.0
1  이영희  33.333333  부산  5200.0
2  박민수  35.000000  미상     0.0
3  최지영  40.000000  대전  4800.0

    이름    나이  도시      급여
0  김철수  25.0  서울  4500.0
1  이영희  25.0  부산  5200.0
2  박민수  35.0  부산  5200.0
3  최지영  40.0  대전  4800.0

## 중복값 확인과 제거
데이터를 수집하거나 병합하는 과정에서 같은 행이 중복으로 들어오는 경우가 있다.
이러한 중복은 집계 결과를 왜곡할 수 있으므로  확인 후 필요하면 제거해야한다.

In [12]:
orders = pd.DataFrame({
    '고객ID': [101, 102, 101, 103, 102],
    '상품': ['A', 'B', 'A', 'C', 'B'],
    '수량': [2, 1, 2, 3, 1]
})

print(orders.duplicated())
print()

# 중복된 행만 보기
display(orders[orders.duplicated()])
# 중복된 행 제거
display(orders.drop_duplicates())
# 고객 아이디 기준 중복 재거
display(orders.drop_duplicates(subset=['고객ID']))

orders

0    False
1    False
2     True
3    False
4     True
dtype: bool

   고객ID 상품  수량
2   101  A   2
4   102  B   1

   고객ID 상품  수량
0   101  A   2
1   102  B   1
3   103  C   3

   고객ID 상품  수량
0   101  A   2
1   102  B   1
3   103  C   3

   고객ID 상품  수량
0   101  A   2
1   102  B   1
2   101  A   2
3   103  C   3
4   102  B   1

## 값 기준 정렬
졍렬 데이터를 크기 순서나 특징 기준에 따라 보기 쉽게 정리할 때 사용한다.
한개의 컬럼으로 정렬할 수도 있고 여러 컬럼을 조합하여 우선 순위를 두고 정렬할 수도 있다

In [14]:
employees = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최지영'],
    '부서': ['개발', '영업', '개발', '인사'],
    '급여': [4500, 5200, 6000, 4800]
})

employees.sort_values('급여')                           # 기본 정렬은 : 오름차순
employees.sort_values('급여', ascending=False)          # ascending=False : 내림차순
employees.sort_values(['부서','급여'], ascending=[True,False])      # 부서 기준 정렬 후 급여 기준 정령

    이름  부서    급여
2  박민수  개발  6000
1  이영희  영업  5200
3  최지영  인사  4800
0  김철수  개발  4500

## 조건 필터링
데이터 전체를 모두 보는 것이 아니라 원하는 조건에 맞는 행만 골라서 확인하는 일이 많다
불리언 인덱싱을 사용하여 조건에 맞는 데이터만 추출할 수 있다.

In [17]:
sales = pd.DataFrame({
    '상품': ['노트북', '마우스', '키보드', '모니터', '헤드셋'],
    '카테고리': ['전자기기', '주변기기', '주변기기', '전자기기', '주변기기'],
    '가격': [1500000, 25000, 45000, 350000, 80000],
    '재고': [10, 50, 0, 15, 25]
})

# 10만원 이상의 가격을 가진 상품만 필터링
sales[sales['가격'] > 100000]
# 다중 조건의 경우
# 5만원 초과하는 가격을 가지고 재고가 있는 상품만 필터링
sales[(sales['가격'] > 50000) & (sales['재고'] > 0)]
# isna : 여러 값 중에 하나에 해당하는지 확인
sales[sales['카테고리'].isin(['전자기기','주변기기'])]

    상품  카테고리       가격  재고
0  노트북  전자기기  1500000  10
1  마우스  주변기기    25000  50
2  키보드  주변기기    45000   0
3  모니터  전자기기   350000  15
4  헤드셋  주변기기    80000  25

### 문자열 조건  필터링
문자열 컬럼은 '.str' 접근자를 이용해 조건을 줄 수 있다.
예를 들어 특정 단어를 포함하는지, 특정 글자로 시작하는지 등을 기준으로 필터링 할 수 있다

In [18]:
# 상품명에 '노트'라는 단어가 포함 되어 있는지?
sales[sales['상품'].str.contains('노트')]
# 상품명이 '헤'라는 단어로 시작하는지?
sales[sales['상품'].str.startswith('헤')]
# 카테고리 명이 '기기'로 끝나느지
sales[sales['카테고리'].str.endswith('기기')]

    상품  카테고리       가격  재고
0  노트북  전자기기  1500000  10
1  마우스  주변기기    25000  50
2  키보드  주변기기    45000   0
3  모니터  전자기기   350000  15
4  헤드셋  주변기기    80000  25

### 범위 조건 필터링
수치 데이터는 특정 구간 안에 들어오는 값만 골라내는 경우가 많다.
예를 들어, 가격대별 상품 조회, 점수 구간 조회등에 활용한다.

In [ ]:
sales[sales['가격'].between(30000,400000)]

## 타입 확인과 변환
데이터를 불러오면서 숫자가 문자열로 들어오거나, 날짜가 일반 텍스트로 저장 되어 있는 경우가 많다.
이 상태에서는 계산이나 날짜 연산이 제대로 되지 않으므로 적절한 타입으로 변환해야 한다.

In [21]:
df_type = pd.DataFrame({
    '날짜': ['2024-01-15', '2024-02-20', '2024-03-25'],
    '금액': ['1000', '2000', '3000'],
    '수량': [10.0, 20.0, 30.0]
})

print(df_type.dtypes)

df_type['금액'] = df_type['금액'].astype(int)       # str -> int
df_type['수량'] = df_type['수량'].astype(int)       # float -> int
df_type['날짜'] = pd.to_datetime(df_type['날짜'])   # str -> datetime
print(df_type.dtypes)

df_type

날짜        str
금액        str
수량    float64
dtype: object
날짜    datetime64[us]
금액             int64
수량             int64
dtype: object

          날짜    금액  수량
0 2024-01-15  1000  10
1 2024-02-20  2000  20
2 2024-03-25  3000  30

## 범주형(category)
문자열 값이 반복되는 컬럼은 'category' 타입으로 바꿔서 관리할 수 있다.
메모리 사용을 줄이고, 범주형 데이터라는 의미를 더 명확하게 표현하는데 도움이 된다.
또한 순서가 있는 범주형 데이터는 직접 순서를 지정할 수 있다.

In [26]:
from pandas.api.types import CategoricalDtype
df_cat = pd.DataFrame({
    '상품': ['A', 'B', 'C', 'D'],
    '카테고리': ['전자기기', '의류', '전자기기', '식품'],
    '사이즈': ['중', '대', '소', '중']
})

df_cat['카테고리'] = df_cat['카테고리'].astype('category')      # 반복 문자열을 범주형으로 변환
print(df_cat.dtypes)
print()

size_type = CategoricalDtype(categories=['소','중','대'],ordered=True)
df_cat['사이즈'] = df_cat['사이즈'].astype(size_type)       # 순서 있는 범주형으로 전환
print(df_cat.dtypes)
print()

df_cat[df_cat['사이즈'] >= '중']

상품           str
카테고리    category
사이즈          str
dtype: object

상품           str
카테고리    category
사이즈     category
dtype: object

  상품  카테고리 사이즈
0  A  전자기기   중
1  B    의류   대
3  D    식품   중