# Transformation
간단한 데이터 변형과 결합을 연습한다.
데이터를 정리하고 보고서용 형태로 바꾸는 기본 흐름에 해당한다.

## apply, map, replace
값을 하나씩 가공하거나, 코드 값을 사람이 읽기 쉬운 값으로 바꾸거나 특정 값을 다른 값으로 치환할 때  사용하는 기능

In [1]:
import pandas as pd
import numpy as np

# 예제 데이터 프레임
df = pd.DataFrame({
    '이름' : ['김철수','이영희','박민수'],
    '점수' : [85,92,78],
    '성별' : ['M','F','M']
})
df

    이름  점수 성별
0  김철수  85  M
1  이영희  92  F
2  박민수  78  M

In [ ]:
# apply : 각 점수에 5점을 더해 조정 점수 컬럼 만들기
# 한 컬럼의 깂을 하나씩 가공할때 사용
df['조정점수'] = df['점수'].apply(lambda x : x + 5)
df

    이름  점수 성별  조정점수
0  김철수  85  M    90
1  이영희  92  F    97
2  박민수  78  M    83

In [4]:
# apply : 함수로 등급 만들기
def grade(x) :
    if x >= 90:
        return 'A'
    elif x >= 80:
        return 'B'
    else:
        return 'C'
df['등급'] = df['점수'].apply(grade)
df

    이름  점수 성별  조정점수 등급
0  김철수  85  M    90  B
1  이영희  92  F    97  A
2  박민수  78  M    83  C

In [5]:
# map : 코드 값을 한글 값으로 매핑
# 성별 코드를 한글 값으로 매핑
gender_map = {'M':'남성','F':'여성'}
df['성별한글'] = df['성별'].map(gender_map)
df

    이름  점수 성별  조정점수 등급 성별한글
0  김철수  85  M    90  B   남성
1  이영희  92  F    97  A   여성
2  박민수  78  M    83  C   남성

In [6]:
# replace : 특정 값만 선택하여 치환
df['등급'] = df['등급'].replace({'B':'B0','C':'C0'})
df

    이름  점수 성별  조정점수  등급 성별한글
0  김철수  85  M    90  B0   남성
1  이영희  92  F    97   A   여성
2  박민수  78  M    83  C0   남성

## np.where, np.select
조건에 따라 새로운 값을 만들 때 사용하는 방식이다.

In [8]:
scores = pd.DataFrame({
    '점수':[95,82,74,61,50]
})

# np.where : 조건이 1개일 때 사용
# 점수가 60점 이상이면 합격, 아니면 불합격
scores['합격'] = np.where(scores['점수'] >= 60,'합격','불합격')

# np.select : 조건이 여러 개일때 사용
# 순서대로 조건을 검사하여 등급을 부여
cond = [
    scores['점수'] >= 90,
    scores['점수'] >= 80,
    scores['점수'] >= 70,
]
choice = ['A','B','C']
scores['등급'] = np.select(cond,choice,default='D')

scores

   점수   합격 등급
0  95   합격  A
1  82   합격  B
2  74   합격  C
3  61   합격  D
4  50  불합격  D

## concat
여러 데이터프레임을 단순히 이어 붙일때 사용한다.
구조가 비슷한 데이터를 아래로 붙이거나, 서로 다른 컬럼을 옆으로 붙일때 사용한다.

In [12]:
df1 = pd.DataFrame({'A':[1,2],'B':[3,4]})
df2 = pd.DataFrame({'A':[5,6],'B':[7,8]})

display(df1)
display(df2)

# 세로 결합 : 행 방향으로 이어 붙이기
pd.concat([df1,df2])
pd.concat([df1,df2],ignore_index=True)      # 기존 인텍스 무시하고 새로 0부터 부여

   A  B
0  1  3
1  2  4

   A  B
0  5  7
1  6  8

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [13]:
# 가로 결합 : 열 방향으로 이어 붙이기
pd.concat([df1,df2],axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

## merge, join
콩통 키를 기준으로 서로 다른 데이터 프레임을 결합할 때 사용한다. 데이터 베이스의 join 개념과 비숫하다.

In [14]:
# 고객 데이터
customers = pd.DataFrame({
    '고객ID': [1, 2, 3, 4],
    '이름': ['김철수', '이영희', '박민수', '최지영']
})

# 주문 데이터
orders = pd.DataFrame({
    '주문ID': [101, 102, 103, 104],
    '고객ID': [1, 2, 2, 5],
    '상품': ['노트북', '마우스', '키보드', '모니터']
})

In [ ]:
# inner join : 양쪽에 모두 존재히는 고객 ID만 남긴다.
pd.merge(customers,orders,on='고객ID',how='inner')

   고객ID   이름  주문ID   상품
0     1  김철수   101  노트북
1     2  이영희   102  마우스
2     2  이영희   103  키보드

In [16]:
# left join : 왼쪽은 모두 유지하고, 오른쪽에 없으면 Nan이 들어간다.
pd.merge(customers,orders,on='고객ID',how='left')

   고객ID   이름   주문ID   상품
0     1  김철수  101.0  노트북
1     2  이영희  102.0  마우스
2     2  이영희  103.0  키보드
3     3  박민수    NaN  NaN
4     4  최지영    NaN  NaN

In [17]:
# outer join : 양쪽 데이터를 모두 살린다.
pd.merge(customers, orders, on='고객ID', how='outer')

   고객ID   이름   주문ID   상품
0     1  김철수  101.0  노트북
1     2  이영희  102.0  마우스
2     2  이영희  103.0  키보드
3     3  박민수    NaN  NaN
4     4  최지영    NaN  NaN
5     5  NaN  104.0  모니터

In [18]:
# join : 인덱스 기준으로 결합
left = pd.DataFrame({'이름':['A','B']},index=['a','b'])
right = pd.DataFrame({'점수':[90,80]},index=['a','b'])

left.join(right)

  이름  점수
a  A  90
b  B  80

## pivot, pivot_table, melt
데이터의 모양을 변경하는 기능이다. 보고서 형태의 표를 만들거나 시각화에 맞는 구조로 변경할 때 사용한다.

In [19]:
# 날짜-지역별 매출 데이터
sales = pd.DataFrame({
    '날짜': ['2024-01', '2024-01', '2024-02', '2024-02'],
    '지역': ['서울', '부산', '서울', '부산'],
    '매출': [100, 80, 120, 90]
})

sales

        날짜  지역   매출
0  2024-01  서울  100
1  2024-01  부산   80
2  2024-02  서울  120
3  2024-02  부산   90

In [20]:
# pivot : 날짜를 행으로, 지역을 열로, 매출을 값으로 배치
# 같은 날짜-지역 조합이면 한 번씩만 있을 때 사용 가능하다.
sales.pivot(index='날짜', columns='지역',values='매출')

지역       부산   서울
날짜
2024-01  80  100
2024-02  90  120

In [22]:
# 중복 키가 있는 데이터
sales2 = pd.DataFrame({
    '날짜': ['2024-01', '2024-01', '2024-01', '2024-02'],
    '지역': ['서울', '서울', '부산', '서울'],
    '매출': [100, 150, 80, 120]
})

# pivot_tabe : 중복 값이 있을 경우 평균으로 집계
sales2.pivot_table(index='날짜',columns='지역',values='매출',aggfunc='mean')

지역         부산     서울
날짜
2024-01  80.0  125.0
2024-02   NaN  120.0

In [23]:
# pivot_tabe : 중복 값이 있을 경우 합계로 집계
sales2.pivot_table(index='날짜',columns='지역',values='매출',aggfunc='sum')

지역         부산     서울
날짜
2024-01  80.0  250.0
2024-02   NaN  120.0

In [24]:
# wide 형태 예제: 과목이 각각의 열로 펼쳐져 있음
wide = pd.DataFrame({
    '이름': ['김철수', '이영희'],
    '국어': [85, 90],
    '영어': [78, 88],
    '수학': [92, 85]
})

wide

    이름  국어  영어  수학
0  김철수  85  78  92
1  이영희  90  88  85

In [ ]:
# melt : wide -> long 변환
# 여러 과목 컬럼을 하나의 과목 컬럼과 점수 컬럼으로 정리
pd.melt(
    wide,
    id_vars='이름',                         # 이 컬럼은 그대로 유지
    value_vars=['국어','영어','수학'],       # 이 컬럼들을 세로로 펼침
    var_name='과목',                        # 기존 컬럼을 처장할 컬럼 이름
    value_name='점수'                       # 실제 값이 들어갈 
)

    이름  과목  점수
0  김철수  국어  85
1  이영희  국어  90
2  김철수  영어  78
3  이영희  영어  88
4  김철수  수학  92
5  이영희  수학  85

## 한 번에 보기
한 가지 기능만 별도로 쓰기 보다는
결합 후 파생 컬럼을 만들고 결과를 다시 정리하는 식으로 여러 기능을 이어서 사용한다.

In [29]:
# 고객 데이터
cust = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '고객명': ['Kim', 'Lee', 'Park']
})

# 주문 데이터
ord = pd.DataFrame({
    '고객ID': [1, 2, 2, 3],
    '금액': [12000, 8000, 15000, 5000]
})

# 고객과 주문 데이터를 고객 ID 기준으로 결합
cust_ord = pd.merge(cust,ord,on='고객ID',how='inner')

# 금액이 10000 이상이면 high, 아니면 low 등급 부여
cust_ord['등급'] = np.where(cust_ord['금액'] >= 10000,'high','loww')
cust_ord

   고객ID   고객명     금액    등급
0     1   Kim  12000  high
1     2   Lee   8000  loww
2     2   Lee  15000  high
3     3  Park   5000  loww